# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 18:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên')),
                ('warranty_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Ngày Bảo Trì')),
                ('producer', models.CharField(blank=True, max_length=30, verbose_name='Hãng SX')),
                ('bienso', models.CharField(max_length=20, verbose_name='Biển Số')),
                ('note', models.TextField(blank=True, verbose_name='Ghi Chú')),
                ('made_in', models.CharField(blank=True, max_length=30, verbose_name='Nơi SX')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Tốt'), (2, 'Bảo Trì'), (3, 'Hỏng')], verbose_name='Tình Trạng')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='driver/%Y/%m/%d/')),
                ('name', models.CharField(max_length=50, verbose_name='Tên')),
                ('license', models.CharField(max_length=50, verbose_name='Bằng Lái')),
                ('address', models.CharField(max_length=100, verbose_name='Địa Chỉ')),
                ('identity', models.CharField(max_length=50, verbose_name='CMNN')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Ngày')),
                ('congviec', models.CharField(max_length=50, verbose_name='Công Việc')),
                ('gia', models.PositiveIntegerField(blank=True, null=True)),
                ('maasset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_tracking.Asset')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='Madriver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset_tracking.Driver'),
        ),
    ]
