# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('warranty_date', models.DateField(blank=True, null=True)),
                ('producer', models.CharField(blank=True, max_length=30)),
                ('bienso', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('made_in', models.CharField(blank=True, max_length=30)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Tốt'), (2, 'Bảo Trì'), (3, 'Hỏng')])),
            ],
        ),
    ]
