# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-29 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='gia',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Giá'),
        ),
    ]
