# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 07:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='warranty_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
