# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 07:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_tracking', '0002_auto_20170726_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='bienso',
            field=models.CharField(max_length=20, verbose_name='Biển Số'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='made_in',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nơi SX'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='note',
            field=models.TextField(blank=True, verbose_name='Ghi Chú'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='producer',
            field=models.CharField(blank=True, max_length=30, verbose_name='Hãng SX'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tốt'), (2, 'Bảo Trì'), (3, 'Hỏng')], verbose_name='Tình Trạng'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='warranty_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Ngày Bảo Trì'),
        ),
    ]
