# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-30 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_tracking', '0002_auto_20170729_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='total',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tốt'), (2, 'Bảo Trì'), (3, 'Hỏng')], default=0, verbose_name='Tình Trạng'),
        ),
    ]
